  0%|          | 0/218607 [00:00<?, ?it/s]
[nltk_data] Downloading package punkt to
[nltk_data]     /afs/csail.mit.edu/u/l/liuguanx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Reading TRAIN images and reports, storing to file...

Traceback (most recent call last):
  File "create_input_files.py", line 10, in <module>
    max_len=100)
  File "/crimea/liuguanx/TieNetReproduction/utils.py", line 196, in create_input_files
    ds = pydicom.dcmread(filename)
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/torch/lib/python3.7/site-packages/pydicom/filereader.py", line 880, in dcmread
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/torch/lib/python3.7/site-packages/pydicom/filereader.py", line 682, in read_partial
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/torch/lib/python3.7/site-packages/pydicom/filereader.py", line 620, in read_preamble
AttributeError: 'list' object has no attribute 'read'
  0%|          | 0/43510 [00:00<?, ?it/s]
[nltk_data] Downloading package punkt to
[nltk_data]     /afs/csail.mit.edu/u/l/liuguanx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Reading TRAIN images and reports, storing to file...

Traceback (most recent call last):
  File "create_input_files.py", line 10, in <module>
    max_len=100)
  File "/crimea/liuguanx/TieNetReproduction/utils.py", line 197, in create_input_files
    plan = dicom.read_file(impaths[i],stop_before_pixels=False)
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/filereader.py", line 614, in read_file
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/filereader.py", line 522, in read_partial
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataset.py", line 258, in __getattr__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataset.py", line 293, in __getitem__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataelem.py", line 306, in DataElement_from_raw
ModuleNotFoundError: No module named 'dicom.values'
  0%|          | 0/43246 [00:00<?, ?it/s]
[nltk_data] Downloading package punkt to
[nltk_data]     /afs/csail.mit.edu/u/l/liuguanx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Reading TRAIN images and captions, storing to file...

Traceback (most recent call last):
  File "create_input_files.py", line 10, in <module>
    max_len=100)
  File "/crimea/liuguanx/TieNetReproduction/utils.py", line 187, in create_input_files
    plan = dicom.read_file(impaths[i],stop_before_pixels=False)
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/filereader.py", line 614, in read_file
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/filereader.py", line 522, in read_partial
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataset.py", line 258, in __getattr__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataset.py", line 293, in __getitem__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/dataelem.py", line 306, in DataElement_from_raw
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/dicom/values.py'
[nltk_data] Downloading package punkt to
[nltk_data]     /afs/csail.mit.edu/u/l/liuguanx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "train.py", line 329, in <module>
    main()
  File "train.py", line 117, in main
    epoch=epoch)
  File "train.py", line 163, in train
    for i, (imgs, caps, caplens) in enumerate(train_loader):
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 253, in __init__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 253, in <listcomp>
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/multiprocessing/context.py", line 101, in Queue
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/multiprocessing/queues.py'
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f831951a128>>
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
  File "/afs/csail.mit.edu/u/l/liuguanx/.conda/envs/mimic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 393, in _shutdown_workers
AttributeError: '_DataLoaderIter' object has no attribute 'worker_pids_set'
